<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEESJxxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEESJxxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEESJxxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEESJxxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEESJxxs\App_KernelDevDebugContainer([
    'container.build_hash' => 'EESJxxs',
    'container.build_id' => '9ba077b5',
    'container.build_time' => 1673547371,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEESJxxs');
