<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVButrXi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVButrXi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVButrXi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVButrXi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVButrXi\App_KernelDevDebugContainer([
    'container.build_hash' => 'VButrXi',
    'container.build_id' => 'af7701e2',
    'container.build_time' => 1673546311,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVButrXi');
