<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerABUby6w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerABUby6w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerABUby6w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerABUby6w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerABUby6w\App_KernelDevDebugContainer([
    'container.build_hash' => 'ABUby6w',
    'container.build_id' => '2a472a5c',
    'container.build_time' => 1673543116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerABUby6w');
