<?php

namespace ContainerAahIGl2;

use Symfony\Bridge\Monolog\Command\ServerLogCommand;
use function dirname;
use const DIRECTORY_SEPARATOR;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Command_ServerLogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'monolog.command.server_log' shared service.
     *
     * @return ServerLogCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once dirname(__DIR__, 4) . '' . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'symfony' . DIRECTORY_SEPARATOR . 'console' . DIRECTORY_SEPARATOR . 'Command' . DIRECTORY_SEPARATOR . 'Command.php';
        include_once dirname(__DIR__, 4) . '' . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'symfony' . DIRECTORY_SEPARATOR . 'monolog-bridge' . DIRECTORY_SEPARATOR . 'Command' . DIRECTORY_SEPARATOR . 'ServerLogCommand.php';

        $container->privates['monolog.command.server_log'] = $instance = new ServerLogCommand();

        $instance->setName('server:log');
        $instance->setDescription('Start a log server that displays logs in real time');

        return $instance;
    }
}
