<?php

namespace ContainerEESJxxs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Adb7W5BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Adb7W5B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Adb7W5B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'match' => ['privates', '.errored..service_locator.Adb7W5B.App\\Entity\\Matches', NULL, 'Cannot autowire service ".service_locator.Adb7W5B": it references class "App\\Entity\\Matches" but no such service exists.'],
        ], [
            'match' => 'App\\Entity\\Matches',
        ]);
    }
}
