<?php

namespace ContainerEESJxxs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dw_JBWoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dw.jBWo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dw.jBWo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::helloWorld' => ['privates', '.service_locator..eapurg', 'get_ServiceLocator__EapurgService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController::loginRedirect' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Controller\\MatchesController::delete' => ['privates', '.service_locator.Z2WMIDX', 'get_ServiceLocator_Z2WMIDXService', true],
            'App\\Controller\\MatchesController::edit' => ['privates', '.service_locator.Z2WMIDX', 'get_ServiceLocator_Z2WMIDXService', true],
            'App\\Controller\\MatchesController::index' => ['privates', '.service_locator.c0tDAYp', 'get_ServiceLocator_C0tDAYpService', true],
            'App\\Controller\\MatchesController::new' => ['privates', '.service_locator.c0tDAYp', 'get_ServiceLocator_C0tDAYpService', true],
            'App\\Controller\\MatchesController::show' => ['privates', '.service_locator.Adb7W5B', 'get_ServiceLocator_Adb7W5BService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\HomeController:helloWorld' => ['privates', '.service_locator..eapurg', 'get_ServiceLocator__EapurgService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController:loginRedirect' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Controller\\MatchesController:delete' => ['privates', '.service_locator.Z2WMIDX', 'get_ServiceLocator_Z2WMIDXService', true],
            'App\\Controller\\MatchesController:edit' => ['privates', '.service_locator.Z2WMIDX', 'get_ServiceLocator_Z2WMIDXService', true],
            'App\\Controller\\MatchesController:index' => ['privates', '.service_locator.c0tDAYp', 'get_ServiceLocator_C0tDAYpService', true],
            'App\\Controller\\MatchesController:new' => ['privates', '.service_locator.c0tDAYp', 'get_ServiceLocator_C0tDAYpService', true],
            'App\\Controller\\MatchesController:show' => ['privates', '.service_locator.Adb7W5B', 'get_ServiceLocator_Adb7W5BService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\HomeController::helloWorld' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\LoginController::loginRedirect' => '?',
            'App\\Controller\\MatchesController::delete' => '?',
            'App\\Controller\\MatchesController::edit' => '?',
            'App\\Controller\\MatchesController::index' => '?',
            'App\\Controller\\MatchesController::new' => '?',
            'App\\Controller\\MatchesController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\HomeController:helloWorld' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\LoginController:loginRedirect' => '?',
            'App\\Controller\\MatchesController:delete' => '?',
            'App\\Controller\\MatchesController:edit' => '?',
            'App\\Controller\\MatchesController:index' => '?',
            'App\\Controller\\MatchesController:new' => '?',
            'App\\Controller\\MatchesController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
