<?php

namespace ContainerEESJxxs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C0tDAYpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c0tDAYp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c0tDAYp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'matchesRepository' => ['privates', 'App\\Repository\\MatchesRepository', 'getMatchesRepositoryService', true],
        ], [
            'matchesRepository' => 'App\\Repository\\MatchesRepository',
        ]);
    }
}
